apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app: lab
  name: lab
  namespace: team-project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: lab
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: lab
        delete: "true"
        stage: dev
    spec:
      containers:
      - image: busybox
        name: busy
        command: ["sleep", "36000"]
        env:
        - name: LOG_LEVEL
          value: DEBUG
        - name: REGISTRY_URI
          valueFrom:
            configMapKeyRef:
              name: registry-uri
              key: uri
        - name: MODELS_URL
          valueFrom:
            secretKeyRef:
              name: models-url
              key: url
        - name: RESULTS_URL
          valueFrom:
            secretKeyRef:
              name: results-url
              key: url
        volumeMounts:
        - name: configs
          mountPath: /root/experiment/configs
          readOnly: true
        - name: data
          mountPath: /mnt/data
          readOnly: true
      volumes:
      - name: configs
        configMap:
          name: test-cm
      - name: data
        persistentVolumeClaim:
          claimName: processed-data-claim
status: {}
