apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  creationTimestamp: null
  name: mlflow-tracking-server
  namespace: team-project
spec:
  rules:
  - host: team-project
    http:
      paths:
      - backend:
          service:
            name: mlflow-tracking-server
            port:
              number: 8885
        path: /mlflow
        pathType: Exact
status:
  loadBalancer: {}
