model:
  name: lda
  preproc_func: power
models_table: sklearn_models
name: vgg16_power_lda
results_table: sklearn_results
test_path: /mnt/data/vgg16/test_data.csv
train_path: /mnt/data/vgg16/train_data.csv
