model:
  name: log_reg
  preproc_func: quantile
models_table: sklearn_models
name: vgg16_quantile_log_reg
results_table: sklearn_results
test_path: /mnt/data/vgg16/test_data.csv
train_path: /mnt/data/vgg16/train_data.csv
