model:
  name: lda
  preproc_func: standard
models_table: sklearn_models
name: xception_standard_lda
results_table: sklearn_results
test_path: /mnt/data/xception/test_data.csv
train_path: /mnt/data/xception/train_data.csv
