model:
  name: log_reg
models_table: sklearn_models
name: xception_none_log_reg
results_table: sklearn_results
test_path: /mnt/data/xception/test_data.csv
train_path: /mnt/data/xception/train_data.csv
