model:
  name: nb
  preproc_func: quantile
models_table: sklearn_models
name: xception_quantile_nb
results_table: sklearn_results
test_path: /mnt/data/xception/test_data.csv
train_path: /mnt/data/xception/train_data.csv
