model:
  name: log_reg
  preproc_func: min_max
models_table: sklearn_models
name: xception_min_max_log_reg
results_table: sklearn_results
test_path: /mnt/data/xception/test_data.csv
train_path: /mnt/data/xception/train_data.csv
