apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    stage: dev
    delete: "true"
  name: experiments-db-dev-svc
  namespace: team-project
spec:
  ports:
  - port: 5432
    protocol: TCP
    targetPort: 5432
  selector:
    app: experiments-db
  type: NodePort
status:
  loadBalancer: {}
